# 블로그 제목
title:        'Na.R.D.'

# 블로그 설명
description:  'I am Rule Destroyer.'

# 블로그 URL
url:          'http://seodaeya.github.io'
baseurl:      '/'

# 소셜 미디어 링크
social:
  github:     'seodaeya'

github:
  repo:       'https://github.com/seodaeya/seodaeya.github.io'
