# 블로그 제목
title:                'Na.R.D.'

# 블로그 설명
description:          'I am Rule Destroyer.'

# 블로그 URL
url:                  'https://seodaeya.github.io'
baseurl:              '/'

# github
link:
  github:             'https://github.com/seodaeya'
  blog:               'https://seodaeya.tistory.com'
  youtube:            'https://www.youtube.com/@Na.R.D.'

# 소셜 미디어 링크(TODO)
social:
  github:             'seodaeya'